
import java.awt.Graphics;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class Main extends javax.swing.JFrame {

    public void generarGalaxia(ArrayList LecturaArchivo) {
        for (int i = 0; i < LecturaArchivo.size(); i++) {
            String[] ARISTA = LecturaArchivo.get(i).toString().split(";");
            vertice vertice1 = new vertice(ARISTA[0]);
            vertice vertice2 = new vertice(ARISTA[2]);
            arista arista_nueva = new arista(Integer.parseInt(ARISTA[1]), vertice1, vertice2);
            galaxia.addArista(arista_nueva);
        }
    }
    
    public String getTextoParaArchivo(ArrayList<arista> aristas){
        String Texto = "";
        for (int i = 0; i < aristas.size()-1; i++) {
            String nombre1 = aristas.get(i).getAnterior().getNombre();
            String nombre2 = aristas.get(i).getSiguiente().getNombre();
            String peso = Integer.toString(aristas.get(i).getPeso());
            Texto += nombre1+";"+peso+";"+nombre2+"\n";
        }
        String nombre1 = aristas.get(aristas.size()-1).getAnterior().getNombre();
        String nombre2 = aristas.get(aristas.size()-1).getSiguiente().getNombre();
        String peso = Integer.toString(aristas.get(aristas.size()-1).getPeso());
        Texto += nombre1+";"+peso+";"+nombre2;
        return Texto;
    }
    
    public void guardarArchivo(ArrayList<arista> aristas) {
        String Texto = getTextoParaArchivo(aristas);
        try {
            String nombre = "";
            JFileChooser file = new JFileChooser();
            file.showSaveDialog(this);
            File guarda = file.getSelectedFile();

            if (guarda != null) {
                /*guardamos el archivo y le damos el formato directamente,
                 * si queremos que se guarde en formato doc lo definimos como .doc*/
                FileWriter save = new FileWriter(guarda + ".txt");
                save.write(Texto);
                save.close();
                JOptionPane.showMessageDialog(null,
                        "El archivo se a guardado Exitosamente",
                        "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,
                    "Su archivo no se ha guardado",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

    }
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_galaxia = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jpm_galaxia = new javax.swing.JPopupMenu();
        CrearPlaneta = new javax.swing.JMenuItem();
        CrearConexion = new javax.swing.JMenuItem();
        Hola = new javax.swing.JMenuItem();
        jd_crear_planeta = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        tf_nuevo_planeta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cb_planetas_existentes = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        sp_peso_nuevo_planeta = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jd_modificar_arista = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        cb_modificar_vertice1 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        cb_modificar_vertice2 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        sp_modificar_peso = new javax.swing.JSpinner();
        jButton6 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        cb_modificar_vertice1_nuevo = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        cb_modificar_vertice2_nuevo = new javax.swing.JComboBox();
        jd_eliminar_arista = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        cb_eliminar_vertice1 = new javax.swing.JComboBox();
        cb_eliminar_vertice2 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jd_dijkstra = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        cb_dijkstra_1 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        cb_dijkstra_2 = new javax.swing.JComboBox();
        jButton10 = new javax.swing.JButton();
        jd_WARP = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        cb_WARP_1 = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        cb_WARP_2 = new javax.swing.JComboBox();
        jButton12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton2.setText("Salir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planet-1.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planet-2.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planet-11.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planet-10.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planet-13.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planet-9.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planet-8.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planet-6.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planet-4.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planet-19.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planet-20.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addGap(160, 160, 160)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(184, 184, 184)
                .addComponent(jLabel15)
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jButton4.setText("Agregar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Modificar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton7.setText("Eliminar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton9.setText("Camino Mas Corto");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton11.setText("WARP");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton13.setText("Guardar");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_galaxiaLayout = new javax.swing.GroupLayout(jd_galaxia.getContentPane());
        jd_galaxia.getContentPane().setLayout(jd_galaxiaLayout);
        jd_galaxiaLayout.setHorizontalGroup(
            jd_galaxiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_galaxiaLayout.createSequentialGroup()
                .addGap(0, 169, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_galaxiaLayout.setVerticalGroup(
            jd_galaxiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_galaxiaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addGroup(jd_galaxiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton7)
                    .addComponent(jButton9)
                    .addComponent(jButton11)
                    .addComponent(jButton13)))
        );

        CrearPlaneta.setText("Crear Planeta");
        CrearPlaneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearPlanetaMouseClicked(evt);
            }
        });
        jpm_galaxia.add(CrearPlaneta);

        CrearConexion.setText("Crear Conección");
        jpm_galaxia.add(CrearConexion);

        Hola.setText("jMenuItem1");
        jpm_galaxia.add(Hola);

        jLabel1.setText("Nombre de Planeta: ");

        jLabel2.setText("Desde que planeta podemos llegar a el: ");

        jLabel3.setText("Años luz que tomaria llegar: ");

        sp_peso_nuevo_planeta.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jButton3.setText("Crear");

        javax.swing.GroupLayout jd_crear_planetaLayout = new javax.swing.GroupLayout(jd_crear_planeta.getContentPane());
        jd_crear_planeta.getContentPane().setLayout(jd_crear_planetaLayout);
        jd_crear_planetaLayout.setHorizontalGroup(
            jd_crear_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_planetaLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tf_nuevo_planeta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jd_crear_planetaLayout.createSequentialGroup()
                .addGroup(jd_crear_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jd_crear_planetaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sp_peso_nuevo_planeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jd_crear_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb_planetas_existentes, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)))
        );
        jd_crear_planetaLayout.setVerticalGroup(
            jd_crear_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_planetaLayout.createSequentialGroup()
                .addGroup(jd_crear_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nuevo_planeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jd_crear_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_planetas_existentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jd_crear_planetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sp_peso_nuevo_planeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        jLabel10.setText("jLabel10");

        jLabel16.setText("Planeta A:");

        jLabel17.setText("Planeta B:");

        jLabel18.setText("Peso:");

        sp_modificar_peso.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jButton6.setText("Modificar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jLabel19.setText("Nuevo A:");

        jLabel20.setText("Nuevo B:");

        javax.swing.GroupLayout jd_modificar_aristaLayout = new javax.swing.GroupLayout(jd_modificar_arista.getContentPane());
        jd_modificar_arista.getContentPane().setLayout(jd_modificar_aristaLayout);
        jd_modificar_aristaLayout.setHorizontalGroup(
            jd_modificar_aristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_aristaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_modificar_aristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificar_aristaLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sp_modificar_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(jd_modificar_aristaLayout.createSequentialGroup()
                        .addGroup(jd_modificar_aristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_modificar_aristaLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(cb_modificar_vertice1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(cb_modificar_vertice2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_modificar_aristaLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(cb_modificar_vertice1_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(cb_modificar_vertice2_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(48, Short.MAX_VALUE))))
        );
        jd_modificar_aristaLayout.setVerticalGroup(
            jd_modificar_aristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_aristaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_modificar_aristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cb_modificar_vertice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(cb_modificar_vertice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jd_modificar_aristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cb_modificar_vertice1_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(cb_modificar_vertice2_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jd_modificar_aristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificar_aristaLayout.createSequentialGroup()
                        .addGroup(jd_modificar_aristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(sp_modificar_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jLabel21.setText("Planeta A:");

        jLabel22.setText("Planeta B:");

        jButton8.setText("Eliminar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_eliminar_aristaLayout = new javax.swing.GroupLayout(jd_eliminar_arista.getContentPane());
        jd_eliminar_arista.getContentPane().setLayout(jd_eliminar_aristaLayout);
        jd_eliminar_aristaLayout.setHorizontalGroup(
            jd_eliminar_aristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminar_aristaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_eliminar_aristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_eliminar_aristaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8))
                    .addGroup(jd_eliminar_aristaLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(cb_eliminar_vertice1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(cb_eliminar_vertice2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(48, Short.MAX_VALUE))))
        );
        jd_eliminar_aristaLayout.setVerticalGroup(
            jd_eliminar_aristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminar_aristaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_eliminar_aristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cb_eliminar_vertice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(cb_eliminar_vertice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jButton8))
        );

        jLabel23.setText("Planeta A:");

        jLabel24.setText("Planeta B:");

        jButton10.setText("Generar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_dijkstraLayout = new javax.swing.GroupLayout(jd_dijkstra.getContentPane());
        jd_dijkstra.getContentPane().setLayout(jd_dijkstraLayout);
        jd_dijkstraLayout.setHorizontalGroup(
            jd_dijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_dijkstraLayout.createSequentialGroup()
                .addGroup(jd_dijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_dijkstraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(cb_dijkstra_1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(cb_dijkstra_2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_dijkstraLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton10)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jd_dijkstraLayout.setVerticalGroup(
            jd_dijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_dijkstraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_dijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cb_dijkstra_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(cb_dijkstra_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addContainerGap())
        );

        jLabel25.setText("Planeta A:");

        jLabel26.setText("Planeta B:");

        jButton12.setText("WARP!!!");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_WARPLayout = new javax.swing.GroupLayout(jd_WARP.getContentPane());
        jd_WARP.getContentPane().setLayout(jd_WARPLayout);
        jd_WARPLayout.setHorizontalGroup(
            jd_WARPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_WARPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(cb_WARP_1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(cb_WARP_2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_WARPLayout.setVerticalGroup(
            jd_WARPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_WARPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_WARPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cb_WARP_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(cb_WARP_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cargar Galaxia");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButton1)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton1)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String aux = "";
        ArrayList texto = new ArrayList();
        try {
            /**
             * llamamos el metodo que permite cargar la ventana
             */
            JFileChooser file = new JFileChooser();
            file.showOpenDialog(this);
            /**
             * abrimos el archivo seleccionado
             */
            File abre = file.getSelectedFile();

            /**
             * recorremos el archivo, lo leemos para plasmarlo en el area de
             * texto
             */
            if (abre != null) {
                FileReader archivo = new FileReader(abre);
                BufferedReader lee = new BufferedReader(archivo);
                while ((aux = lee.readLine()) != null) {
                    texto.add(aux);
                }
                lee.close();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex + ""
                    + "\nNo se ha encontrado el archivo",
                    "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }
        generarGalaxia(texto);
        ArrayList NOMBRES = galaxia.getNombres();
        Graphics g = this.jPanel1.getGraphics();
        this.jLabel13.setVisible(false);
        this.jLabel14.setVisible(false);
        this.jLabel15.setVisible(false);
        this.jd_galaxia.pack();
        this.jd_galaxia.setLocationRelativeTo(this);
        this.jd_galaxia.setModal(true);
        this.jd_galaxia.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked
    private void CrearPlanetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearPlanetaMouseClicked
        // codigo para crear un planeta o cargarlo en el panel
        this.jpm_galaxia.setVisible(false);
        this.jd_crear_planeta.pack();
        this.jd_crear_planeta.setModal(true);
        this.jd_crear_planeta.setVisible(true);
    }//GEN-LAST:event_CrearPlanetaMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // evento para crear un nuevo planeta
        String nombre = JOptionPane.showInputDialog(this, "Ingrese Nombre del Planeta");
        String peso = JOptionPane.showInputDialog(this, "Ingrese peso");
        String nombre2 = JOptionPane.showInputDialog(this, "De cual planeta llegamos a este?");
        vertice vertice1 = new vertice(nombre);
        vertice vertice2 = new vertice(nombre2);
        arista arista_nueva = new arista(Integer.parseInt(peso), vertice1, vertice2);
        galaxia.addArista(arista_nueva);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // boton para ir al dialogo de modificar
        ArrayList nombres = galaxia.getNombres();
        for (int i = 0; i < nombres.size(); i++) {
            this.cb_modificar_vertice1.addItem(nombres.get(i).toString());
            this.cb_modificar_vertice2.addItem(nombres.get(i).toString());
            this.cb_modificar_vertice1_nuevo.addItem(nombres.get(i).toString());
            this.cb_modificar_vertice2_nuevo.addItem(nombres.get(i).toString());
        }
        this.jd_modificar_arista.pack();
        this.jd_modificar_arista.setModal(true);
        this.jd_modificar_arista.setLocationRelativeTo(this);
        this.jd_modificar_arista.setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // boton modificar en el dialogo modificar
        String nombre1 = this.cb_modificar_vertice1.getSelectedItem().toString();
        String nombre2 = this.cb_modificar_vertice2.getSelectedItem().toString();
        String nombre1_nuevo = this.cb_modificar_vertice1_nuevo.getSelectedItem().toString();
        String nombre2_nuevo = this.cb_modificar_vertice2_nuevo.getSelectedItem().toString();
        int peso = Integer.parseInt(this.sp_modificar_peso.getValue().toString());
        if (galaxia.ModificarArista(nombre1, nombre2, nombre1_nuevo, nombre2_nuevo, peso)) {
            JOptionPane.showMessageDialog(this, "Exito modifico el nuevo camino");
            this.jd_modificar_arista.setVisible(false);
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // boton eliminar en dialogo eliminar arista
        String nombre1 = this.cb_eliminar_vertice1.getSelectedItem().toString();
        String nombre2 = this.cb_eliminar_vertice2.getSelectedItem().toString();
        if (galaxia.EliminarArista(nombre1, nombre2)) {
            JOptionPane.showMessageDialog(this, "Borro exitosamente");
            this.jd_eliminar_arista.setVisible(false);
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // boton eliminar en dialogo de galaxia
        ArrayList nombres = galaxia.getNombres();
        for (int i = 0; i < nombres.size(); i++) {
            this.cb_eliminar_vertice1.addItem(nombres.get(i).toString());
            this.cb_eliminar_vertice2.addItem(nombres.get(i).toString());
        }
        this.jd_eliminar_arista.pack();
        this.jd_eliminar_arista.setModal(true);
        this.jd_eliminar_arista.setLocationRelativeTo(this);
        this.jd_eliminar_arista.setVisible(true);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // boton camino mas corto en el dialogo de galaxia
        ArrayList nombres = galaxia.getNombres();
        for (int i = 0; i < nombres.size(); i++) {
            this.cb_dijkstra_1.addItem(nombres.get(i).toString());
            this.cb_dijkstra_2.addItem(nombres.get(i).toString());
        }
        this.jd_dijkstra.pack();
        this.jd_dijkstra.setModal(true);
        this.jd_dijkstra.setLocationRelativeTo(this);
        this.jd_dijkstra.setVisible(true);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // Boton Generar en dialogo de dijkstra
        String nombre1 = this.cb_dijkstra_1.getSelectedItem().toString();
        String nombre2 = this.cb_dijkstra_2.getSelectedItem().toString();

    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // boton WARP desde dialogo de galaxia
        ArrayList nombres = galaxia.getNombres();
        for (int i = 0; i < nombres.size(); i++) {
            this.cb_WARP_1.addItem(nombres.get(i).toString());
            this.cb_WARP_2.addItem(nombres.get(i).toString());
        }
        this.jd_WARP.pack();
        this.jd_WARP.setModal(true);
        this.jd_WARP.setLocationRelativeTo(this);
        this.jd_WARP.setVisible(true);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // boton WARP desde dialogo WARP
        if (this.WARP != 0) {
            String nombre1 = this.cb_WARP_1.getSelectedItem().toString();
            String nombre2 = this.cb_WARP_2.getSelectedItem().toString();
            if (galaxia.WARP(nombre1, nombre2)) {
                JOptionPane.showMessageDialog(this, "Logro Doblar el espacio!!");
                WARP--;
                this.jd_WARP.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Algun dato esta incorrecto, intente denuevo");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Solo se puede usar WARP 2 veces no se vago.");
        }
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // evento guardar para guardar la resporteria
        this.guardarArchivo(galaxia.getAristas());
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.jd_galaxia.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CrearConexion;
    private javax.swing.JMenuItem CrearPlaneta;
    private javax.swing.JMenuItem Hola;
    private javax.swing.JComboBox cb_WARP_1;
    private javax.swing.JComboBox cb_WARP_2;
    private javax.swing.JComboBox cb_dijkstra_1;
    private javax.swing.JComboBox cb_dijkstra_2;
    private javax.swing.JComboBox cb_eliminar_vertice1;
    private javax.swing.JComboBox cb_eliminar_vertice2;
    private javax.swing.JComboBox cb_modificar_vertice1;
    private javax.swing.JComboBox cb_modificar_vertice1_nuevo;
    private javax.swing.JComboBox cb_modificar_vertice2;
    private javax.swing.JComboBox cb_modificar_vertice2_nuevo;
    private javax.swing.JComboBox cb_planetas_existentes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDialog jd_WARP;
    private javax.swing.JDialog jd_crear_planeta;
    private javax.swing.JDialog jd_dijkstra;
    private javax.swing.JDialog jd_eliminar_arista;
    private javax.swing.JDialog jd_galaxia;
    private javax.swing.JDialog jd_modificar_arista;
    private javax.swing.JPopupMenu jpm_galaxia;
    private javax.swing.JSpinner sp_modificar_peso;
    private javax.swing.JSpinner sp_peso_nuevo_planeta;
    private javax.swing.JTextField tf_nuevo_planeta;
    // End of variables declaration//GEN-END:variables
Grafo galaxia = new Grafo();
    int WARP = 2;
}
